### ISSUE TITLE
As a user, I want to be able to look up a stock price by company id

### ISSUE THREAD

**Issue by rashir01** [SJROHRXD/groupproject1#8]
## Subtasks
- [x] Add text field where user can enter search term
- [x] Add area where the data is displayed
- [x] Add modal for invalid company name

## Effort Estimation
TBD

## Acceptance criteria
1. When providing a valid company symbol, I am presented with data about the company
2. When adding an invalid company symbol, I am presented with a meaningful message
